# Generated by Django 5.0.4 on 2024-04-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=60, null=True)),
                ('auth_key', models.CharField(blank=True, max_length=32, null=True)),
                ('access_token', models.CharField(max_length=40)),
                ('logged_at', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
                ('isNewUser', models.BooleanField(default=False)),
                ('block_version', models.SmallIntegerField(default=1)),
                ('acceptedTermsId', models.IntegerField(default=None)),
                ('acceptedTermsDate', models.IntegerField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': True,
            },
        ),
    ]
