# Generated by Django 5.0.4 on 2024-04-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluser',
            old_name='acceptedTermsDate',
            new_name='accepted_terms_date',
        ),
        migrations.RenameField(
            model_name='tbluser',
            old_name='acceptedTermsId',
            new_name='accepted_terms_id',
        ),
        migrations.RenameField(
            model_name='tbluser',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='tbluser',
            old_name='isNewUser',
            new_name='is_new_user',
        ),
    ]
