# Generated by Django 5.0.4 on 2024-04-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt_app', '0002_rename_acceptedtermsdate_tbluser_accepted_terms_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_code', models.CharField(max_length=255, null=True)),
                ('give_level', models.SmallIntegerField(null=True)),
                ('receive_level', models.SmallIntegerField(null=True)),
                ('total_received', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('blocked_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('account_type_code', models.SmallIntegerField(null=True)),
                ('child_members_count', models.SmallIntegerField(null=True)),
                ('direct_member_count', models.SmallIntegerField(null=True)),
                ('status_code', models.SmallIntegerField(null=True)),
                ('created_at', models.IntegerField(null=True)),
                ('updated_at', models.IntegerField(null=True)),
                ('profile_status_code', models.SmallIntegerField(null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('deactivation_status', models.SmallIntegerField(null=True)),
                ('card_avatar', models.CharField(max_length=255, null=True)),
                ('permanent_address_same_as_living', models.BooleanField(null=True)),
                ('activated_at', models.IntegerField(null=True)),
                ('total_received_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('invitation_count', models.SmallIntegerField(default=0)),
                ('is_pending_genealogy', models.BooleanField(default=False)),
                ('is_refund_policy_active', models.BooleanField(default=False)),
                ('refund_policy_ends_at', models.DateField(null=True)),
                ('total_spend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accumulated_received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_seen', models.CharField(max_length=100, null=True)),
                ('total_joined_givers', models.SmallIntegerField(default=0)),
                ('is_whatsapp_number_verified', models.BooleanField(default=False)),
                ('blocking_exception', models.BooleanField(default=False)),
                ('exception_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('is_profile_updated', models.BooleanField(default=False)),
                ('parent_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to='gnt_app.tbluser')),
                ('reference_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_user', to='gnt_app.tbluser')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gnt_app.tbluser')),
            ],
        ),
    ]
