# Generated by Django 5.0.4 on 2024-04-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt_app', '0004_rename_user_id_members_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=20, null=True)),
                ('living_address_house_no', models.CharField(blank=True, max_length=20, null=True)),
                ('living_address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('living_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('living_address_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('living_address_ward_no', models.CharField(blank=True, max_length=20, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='gnt_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='MemberNomineeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_contact_number', models.CharField(max_length=255)),
                ('nominee_relationship', models.CharField(max_length=255)),
                ('nominee_adharcard_number', models.CharField(max_length=255)),
                ('nominee_adharcard_image', models.CharField(max_length=255)),
                ('nominee_image', models.CharField(max_length=255)),
                ('nominee_adharcard_image_back', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='gnt_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPaymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_info', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal', models.CharField(blank=True, max_length=255, null=True)),
                ('paytm', models.CharField(blank=True, max_length=255, null=True)),
                ('phonepe', models.CharField(blank=True, max_length=255, null=True)),
                ('bhim_upi', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_pay', models.CharField(blank=True, max_length=255, null=True)),
                ('google_pay', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_registered_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('upi_registered_bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_registered_bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_registered_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='gnt_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPersonalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group_code', models.CharField(max_length=5)),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='gnt_app.members')),
            ],
        ),
    ]
