# Generated by Django 5.0.4 on 2024-04-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt_app', '0006_alter_memberpersonalinfo_blood_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='blood_group_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberpersonalinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
